---
- name: Test SSH connectivity
  hosts: test_server
  gather_facts: false
  tasks:
    - name: Test SSH connection
      ansible.builtin.ping:
      register: ping_result

    - name: Display connection result
      ansible.builtin.debug:
        var: ping_result

    - name: Get remote hostname
      ansible.builtin.command: hostname
      register: hostname_result
      changed_when: true

    - name: Display hostname
      ansible.builtin.debug:
        var: hostname_result.stdout

    - name: Test elevation pwd
      become: true
      become_method: ansible.builtin.sudo
      become_user: 'arian'
      # become_exe: "sudo su - "
      ansible.builtin.command: 'pwd'
      register: elevation_result
      changed_when: true

    - name: Show elevation result
      ansible.builtin.debug:
        var: elevation_result.stdout

    - name: Test elevation shell
      become: true
      become_user: arian
      become_flags: "sudo su - arian -c"
      ansible.builtin.command: 'pwd'
      register: elevation_result
      changed_when: true

    - name: Show elevation result
      ansible.builtin.debug:
        var: elevation_result.stdout
